spring:
  datasource:
    url: jdbc:mariadb://3.22.110.182:3306/jsyang
    #    url: jdbc:mariadb://localhost:3306/jsyang
    username: jsyang
    password: jsyang
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug